version: "3"
services:

  web:
    image: golosblockchain/ui-messenger:latest
    restart: always
    build: .    
    volumes:
      - ./config/default.json:/var/app/config/default.json
    ports:
      - "8080:8080"
